import {
    Homepage,
    SmartWatch,
    NeckBand,
    Getintouch,
    TermsAndConditions,
    CommingSoon,
    FAQPage,
    ProductRegistrationpage,
    InputPra,
    DeliveryReturns,
    About,
    Login,
    Signup,
    Wishlist,
    ShoppingCart,
    Checkout,
    MyAccount,
    ProductDetails,
    MyOrdersView,
    Category,
    Admin

} from '../components/pages'

export const Routes = [
    {
        path: "/",
        title: "/home",
        exact: true,
        component: () => <Homepage />,
    },
    {
        path: "/smartwatch",
        title: "/smartwatch",
        exact: true,
        component: () => <SmartWatch />,
    },
    {
        path: "/category",
        title: "/category",
        exact: true,
        component: () => <Category />,
    },
    {
        path: "/neckband",
        title: "/neckband",
        exact: true,
        component: () => <NeckBand />,
    },
    {
        path: "/getintouch",
        title: "/getintouch",
        exact: true,
        component: () => <Getintouch />,
    },
    {
        path: "/termsandconditions",
        title: "/termsandconditions",
        exact: true,
        component: () => <TermsAndConditions />,
    },
    {
        path: "/faqs",
        title: "/faqs",
        exact: true,
        component: () => <FAQPage />,
    },
    {
        path: "/commingsoon",
        title: "/commingsoon",
        exact: true,
        component: () => <CommingSoon />,
    },
    {
        path: "/warranty",
        title: "/warranty",
        exact: true,
        component: () => <ProductRegistrationpage />,
    },
    {
        path: "/inputpra",
        title: "/inputpra",
        exact: true,
        component: () => <InputPra />,
    },
    {
        path: "/returns",
        title: "/returns",
        exact: true,
        component: () => <DeliveryReturns />,
    },
    {
        path: "/about",
        title: "/about",
        exact: true,
        component: () => <About />,
    },
    {
        path: "/login",
        title: "/login",
        exact: true,
        component: () => <Login />,
    },
    {
        path: "/signup",
        title: "/signup",
        exact: true,
        component: () => <Signup />,
    },
    {
        path: "/wishlist",
        title: "/wishlist",
        exact: true,
        component: () => <Wishlist />,
    },
    {
        path: "/shoppingcart",
        title: "/shoppingcart",
        exact: true,
        component: () => <ShoppingCart />,
    },
    {
        path: "/checkout",
        title: "/checkout",
        exact: true,
        component: () => <Checkout />,
    },
    {
        path: "/myaccount",
        title: "/myaccount",
        exact: true,
        component: () => <MyAccount />,
    },
    {
        path: "/myordersview",
        title: "/myordersview",
        exact: true,
        component: () => <MyOrdersView />,
    },
    {
        path: "/product/:productID",
        title: "/product/:productID",
        exact: true,
        component: () => <ProductDetails />,
    },
    {
        path: "/admin",
        title: "/admin",
        exact: true,
        component: () => <Admin />,
    },
]
